site_name: "pySSMF Documentation"
site_description: |
  oySSMF Documentation for strongly correlated systems
site_author: JoseMPizarro
repo_url: https://github.com/JosePizarro3/pySSMF
nav:
  - Home: index.md
theme:
  name: material
  font:
    text: 'Titillium Web'
  features:
    - navigation.instant
plugins:
  - search
