name: install-and-test
on: [push]
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install '.[dev]'
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional src/pyssmf tests
    - name: Test with pytest
      run: |
        python -m pytest -sv tests
  build-and-install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Build the package
      run: |
        pip install --upgrade pip
        pip install build
        python -m build --sdist
    - name: Install the package
      run: |
        pip install dist/*.tar.gz
  ruff-linting:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: chartboost/ruff-action@v1
          with:
            args: "check ."
  ruff-formatting:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: chartboost/ruff-action@v1
          with:
            args: "format . --check --verbose"
